//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/player_action.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActionKeybind: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActionKeybind()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""player_action"",
    ""maps"": [
        {
            ""name"": ""main_action"",
            ""id"": ""0b5a9205-4bc2-423f-9d40-ebf8d8ec4878"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7f7a372f-82ca-47f8-9987-9efd41cddbe0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""3981ec11-6dba-48de-815c-35cb896c8335"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Value"",
                    ""id"": ""5873acaf-ddcc-4abd-ac5a-6af6d6a005dd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack/Interact"",
                    ""type"": ""Value"",
                    ""id"": ""03d2e960-0651-4fe3-9cd2-2fef4765e4f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SkillAttack1"",
                    ""type"": ""Button"",
                    ""id"": ""591f66b4-3963-426b-9145-3c1499d45c87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillAttack2"",
                    ""type"": ""Button"",
                    ""id"": ""aec14269-85da-4cf4-98b8-c3f9e35be2bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillAttack3"",
                    ""type"": ""Button"",
                    ""id"": ""1d267002-725f-43e8-88df-213ec013c454"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""b28cd877-071b-48de-8355-cbf84f324237"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch"",
                    ""type"": ""Value"",
                    ""id"": ""20c40aad-84fc-44c5-b7f3-983ec2aec4a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""82b753fe-98ce-4b31-92f4-8cbf20e7de50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item"",
                    ""type"": ""Value"",
                    ""id"": ""8c9df8ce-aa51-4e86-8cff-5f0afa3412f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""PC Keyboard"",
                    ""id"": ""6fe7f107-2aa8-430c-9c8a-9c49d5ffc940"",
                    ""path"": ""3DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9392d5c6-05e3-4944-a71c-148f9899f64b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ef68edf1-79d0-4ae2-9f31-86ab757e0ea8"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""21be6606-0542-4512-a709-30c129975803"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9ee98392-7410-4073-9c67-e30d056f55c7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""6d93ce6d-a7d1-4c9c-9f46-5d973241963f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""b6f53661-f450-484e-87a7-c66dfa7fe8f9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""e71cc48a-6171-41f8-b74c-b045a4542846"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9b48b850-9b70-4f08-bde9-79d6d9baf90d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""059ff98f-0c4c-4668-ba39-434f0a1f1423"",
                    ""path"": ""<Gamepad>/crossButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""de1ed1de-305c-4228-90b4-e0fe5dd45ce3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b5066b65-b936-4c8f-97fc-28acc457c093"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""55346f88-8017-41d0-83b1-4ba02af34116"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""9408af9f-6610-45f8-a0b5-924565cdcd55"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""18cb32e8-82bf-40ca-aecc-a78bb25f1ff7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""052229bf-953c-4e85-b794-84c25650a05e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""655dc4f5-6903-4fe8-96bc-5b42fa98c8b1"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5f9d14c0-0250-4d72-a3fb-50e7aea3619e"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c9106a4b-87e5-4bbc-b453-e4cb90347388"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8db584ad-f5e8-465f-b621-b1d394d39e82"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2f776ff1-4162-4460-bc66-f9048b3d2624"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04510c68-70e4-48d5-85ac-15e85589a087"",
                    ""path"": ""<Gamepad>/startButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa8c969e-4f4c-4a9c-80b7-b1ce4104575f"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack/Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acfcb5ee-7cc0-4a77-93b2-ad24e69bd20f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack/Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30b5f43e-419d-49bf-93ca-9e32a19e9fcc"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""add70e6a-978b-414c-a2c6-89536e33634c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff225cd6-06d5-4b8c-b709-7722a1bd34c2"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""cefbe0d3-816d-458f-9299-931820fe9bf9"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""77ba5f5f-d8d4-43f6-946f-9a8aac2e5eb4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""28b63b7e-f525-4b77-9866-496450d1170c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""496cddcc-5087-4175-acac-8aadf1a24e74"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""e61e9de2-3cae-4dc2-b35a-05c0a2009e08"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""b6dd1611-8b82-4f69-8517-af6f0193725e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""e93bcac3-312c-4192-851d-1b7e06f0238e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillAttack3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1b37bd1c-48da-4a23-93d4-87299b1ad1e5"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f55f0a0b-d5fe-4839-bfcc-e5b1da273734"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e8e93e8-cf62-4000-931e-9ebc8cc1a192"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""f9aa0aa0-a064-4271-8405-7bd41896036e"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""69298290-c35f-4b8d-b9fd-f4b6c2e926af"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""8bdcae80-c333-4b3c-8f27-83870467bdd6"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""11693533-bc3d-4f13-9348-8fdfabbf2737"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""d6e5de42-8133-4e5e-9a03-b9dfb967894a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""81d1a129-761e-4e8f-836e-5088d57547c7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a4d674fe-c473-40b9-973f-7a5a6b8bf92d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b18606f8-753c-4054-b874-4f5a822725c2"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efeddcfd-2a19-4189-a7f0-6e1fd170542f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // main_action
        m_main_action = asset.FindActionMap("main_action", throwIfNotFound: true);
        m_main_action_Move = m_main_action.FindAction("Move", throwIfNotFound: true);
        m_main_action_Look = m_main_action.FindAction("Look", throwIfNotFound: true);
        m_main_action_Menu = m_main_action.FindAction("Menu", throwIfNotFound: true);
        m_main_action_AttackInteract = m_main_action.FindAction("Attack/Interact", throwIfNotFound: true);
        m_main_action_SkillAttack1 = m_main_action.FindAction("SkillAttack1", throwIfNotFound: true);
        m_main_action_SkillAttack2 = m_main_action.FindAction("SkillAttack2", throwIfNotFound: true);
        m_main_action_SkillAttack3 = m_main_action.FindAction("SkillAttack3", throwIfNotFound: true);
        m_main_action_Dash = m_main_action.FindAction("Dash", throwIfNotFound: true);
        m_main_action_Switch = m_main_action.FindAction("Switch", throwIfNotFound: true);
        m_main_action_Block = m_main_action.FindAction("Block", throwIfNotFound: true);
        m_main_action_Item = m_main_action.FindAction("Item", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // main_action
    private readonly InputActionMap m_main_action;
    private List<IMain_actionActions> m_Main_actionActionsCallbackInterfaces = new List<IMain_actionActions>();
    private readonly InputAction m_main_action_Move;
    private readonly InputAction m_main_action_Look;
    private readonly InputAction m_main_action_Menu;
    private readonly InputAction m_main_action_AttackInteract;
    private readonly InputAction m_main_action_SkillAttack1;
    private readonly InputAction m_main_action_SkillAttack2;
    private readonly InputAction m_main_action_SkillAttack3;
    private readonly InputAction m_main_action_Dash;
    private readonly InputAction m_main_action_Switch;
    private readonly InputAction m_main_action_Block;
    private readonly InputAction m_main_action_Item;
    public struct Main_actionActions
    {
        private @PlayerActionKeybind m_Wrapper;
        public Main_actionActions(@PlayerActionKeybind wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_main_action_Move;
        public InputAction @Look => m_Wrapper.m_main_action_Look;
        public InputAction @Menu => m_Wrapper.m_main_action_Menu;
        public InputAction @AttackInteract => m_Wrapper.m_main_action_AttackInteract;
        public InputAction @SkillAttack1 => m_Wrapper.m_main_action_SkillAttack1;
        public InputAction @SkillAttack2 => m_Wrapper.m_main_action_SkillAttack2;
        public InputAction @SkillAttack3 => m_Wrapper.m_main_action_SkillAttack3;
        public InputAction @Dash => m_Wrapper.m_main_action_Dash;
        public InputAction @Switch => m_Wrapper.m_main_action_Switch;
        public InputAction @Block => m_Wrapper.m_main_action_Block;
        public InputAction @Item => m_Wrapper.m_main_action_Item;
        public InputActionMap Get() { return m_Wrapper.m_main_action; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Main_actionActions set) { return set.Get(); }
        public void AddCallbacks(IMain_actionActions instance)
        {
            if (instance == null || m_Wrapper.m_Main_actionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Main_actionActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @AttackInteract.started += instance.OnAttackInteract;
            @AttackInteract.performed += instance.OnAttackInteract;
            @AttackInteract.canceled += instance.OnAttackInteract;
            @SkillAttack1.started += instance.OnSkillAttack1;
            @SkillAttack1.performed += instance.OnSkillAttack1;
            @SkillAttack1.canceled += instance.OnSkillAttack1;
            @SkillAttack2.started += instance.OnSkillAttack2;
            @SkillAttack2.performed += instance.OnSkillAttack2;
            @SkillAttack2.canceled += instance.OnSkillAttack2;
            @SkillAttack3.started += instance.OnSkillAttack3;
            @SkillAttack3.performed += instance.OnSkillAttack3;
            @SkillAttack3.canceled += instance.OnSkillAttack3;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Switch.started += instance.OnSwitch;
            @Switch.performed += instance.OnSwitch;
            @Switch.canceled += instance.OnSwitch;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
            @Item.started += instance.OnItem;
            @Item.performed += instance.OnItem;
            @Item.canceled += instance.OnItem;
        }

        private void UnregisterCallbacks(IMain_actionActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @AttackInteract.started -= instance.OnAttackInteract;
            @AttackInteract.performed -= instance.OnAttackInteract;
            @AttackInteract.canceled -= instance.OnAttackInteract;
            @SkillAttack1.started -= instance.OnSkillAttack1;
            @SkillAttack1.performed -= instance.OnSkillAttack1;
            @SkillAttack1.canceled -= instance.OnSkillAttack1;
            @SkillAttack2.started -= instance.OnSkillAttack2;
            @SkillAttack2.performed -= instance.OnSkillAttack2;
            @SkillAttack2.canceled -= instance.OnSkillAttack2;
            @SkillAttack3.started -= instance.OnSkillAttack3;
            @SkillAttack3.performed -= instance.OnSkillAttack3;
            @SkillAttack3.canceled -= instance.OnSkillAttack3;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Switch.started -= instance.OnSwitch;
            @Switch.performed -= instance.OnSwitch;
            @Switch.canceled -= instance.OnSwitch;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
            @Item.started -= instance.OnItem;
            @Item.performed -= instance.OnItem;
            @Item.canceled -= instance.OnItem;
        }

        public void RemoveCallbacks(IMain_actionActions instance)
        {
            if (m_Wrapper.m_Main_actionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMain_actionActions instance)
        {
            foreach (var item in m_Wrapper.m_Main_actionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Main_actionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Main_actionActions @main_action => new Main_actionActions(this);
    public interface IMain_actionActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnAttackInteract(InputAction.CallbackContext context);
        void OnSkillAttack1(InputAction.CallbackContext context);
        void OnSkillAttack2(InputAction.CallbackContext context);
        void OnSkillAttack3(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSwitch(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnItem(InputAction.CallbackContext context);
    }
}
